### PR TITLE
Added non-mapped, variable-coefficient riemann solvers to riemann directory

### PR DESCRIPTION
**Pull request by cjvogl**

### CODE REVIEW

**Comment by cjvogl** [comment]
Forgot about the directory structure you mentioned... going to move these into a "src" directory

**Comment by rjleveque** [comment]
Do we want to put these in src/3d, so we can also have src/2d? 

Note: Eventually I think we plan to move these Riemann solvers into the Riemann repository, but collecting things here for development purposes.

**Comment by cjvogl** [comment]
Good point, I'll make the change.  I also plan on getting a simple example commited on this PR.  Do we want the same 2d/3d structure for the example directory, or just specify 2d/3d in the example name?

**Comment by ketch** [comment]
These will be great to have.

What is the argument against putting these directly into clawpack/riemann?  Seems like we're just creating the extra task of moving them later.

**Comment by cjvogl** [comment]
They've only been tested in one application so far.  I'd like to have them used in one more application (this layered seismic example that should be ready soon) before moving them into clawpack/riemann... just to build my confidence in them.

**Comment by rjleveque** [comment]
Or we could just put them on a branch in clawpack/remann for now without merging them in.

**Comment by mandli** [comment]
+1 for putting them in Riemann.  An alternative you might consider is having this as an app submodule which could be done directly through this repository although maybe it would make more sense to have you "own" the app for the time being at least.

**Comment by cjvogl** [comment]
Sounds like the general consensus is to put them into clawpack/riemann, possible under an "elasticity" branch until they are tested further.  If so, I don't think I have write access to create said branch (or do I?).

**Comment by rjleveque** [comment]
I'll set up a branch in clawpack/riemann.

@ketch and @mandli: Eventually we plan to put some of this in clawpack/apps, but for development we're thinking a separate repository is easier since we'll be collaborating on some non-clawpack code to start (with @dlgeorge and Roger Denlinger to merge with some of his code, and @smoe1 wants to compare with DG methods).

**Comment by rjleveque** [comment]
I just pushed a new branch clawpack/riemann/elasticity with the 3 Riemann solver routines, so I suggest closing this PR.

**Comment by mandli** [comment]
The submodule approach works well with this type of idea since eventually this can be incorporated directly in apps.  The confusing thing though would be if it was eventually incorporated into apps but there was a separate repository that Clawpack owned.  I guess I would favor it being owned by @cjvogl for the time being and being incorporated directly into the apps repository now.

**Pull request closed without merging**
